CREATE TABLE IF NOT EXISTS `testdb`.`USER` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `ID` VARCHAR(20) NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`UID`)
);

CREATE TABLE IF NOT EXISTS `testdb`.`TOWN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE
);

CREATE TABLE IF NOT EXISTS `testdb`.`TOWN LIST` (
  `TOWN_ID` INT NOT NULL,
  `USER_UID` INT NOT NULL,
  `isActive` TINYINT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`TOWN_ID`, `USER_UID`),
  INDEX `fk_TOWN_has_USER_USER1_idx` (`USER_UID` ASC) VISIBLE,
  INDEX `fk_TOWN_has_USER_TOWN1_idx` (`TOWN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TOWN_has_USER_TOWN1`
    FOREIGN KEY (`TOWN_ID`)
    REFERENCES `testdb`.`TOWN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOWN_has_USER_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`PRODUCT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_LIST_ID` INT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `category` VARCHAR(12) NOT NULL,
  `content` TEXT NOT NULL,
  `price` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  `USER_UID` INT NOT NULL,
  PRIMARY KEY (`ID`, `PRODUCT_LIST_ID`, `USER_UID`),
  INDEX `fk_PRODUCT_USER1_idx` (`USER_UID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`PRODUCT_IMAGES` (
  `ID` INT NOT NULL,
  `image_url` VARCHAR(45) NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`ID`, `PRODUCT_ID`),
  INDEX `fk_PRODUCT_IMAGES_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_IMAGES_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `testdb`.`PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`CHAT_ROOM` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_UID` INT NOT NULL,
  `seller_UID` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  `last_chat_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`ID`, `USER_UID`),
  INDEX `fk_CHAT_ROOM_USER1_idx` (`USER_UID` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_ROOM_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`CHAT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `CHAT_ROOM_ID` INT NOT NULL,
  `speaker_UID` INT NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT  now(),
  PRIMARY KEY (`ID`, `CHAT_ROOM_ID`),
  INDEX `fk_CHAT_CHAT_ROOM_idx` (`CHAT_ROOM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CHAT_CHAT_ROOM`
    FOREIGN KEY (`CHAT_ROOM_ID`)
    REFERENCES `testdb`.`CHAT_ROOM` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
