CREATE TABLE IF NOT EXISTS `testdb`.`USER` (
  `UID` INT NOT NULL AUTO_INCREMENT,
  `ID` VARCHAR(20) NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`UID`),
  UNIQUE INDEX `UID_UNIQUE` (`UID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
);

CREATE TABLE IF NOT EXISTS `testdb`.`TOWN` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE
);

CREATE TABLE IF NOT EXISTS `testdb`.`TOWN_LIST` (
  `TOWN_ID` INT NOT NULL,
  `USER_UID` INT NOT NULL,
  `is_active` TINYINT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  `timeupdated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`TOWN_ID`, `USER_UID`),
  INDEX `fk_TOWN_has_USER_USER1_idx` (`USER_UID` ASC) VISIBLE,
  INDEX `fk_TOWN_has_USER_TOWN1_idx` (`TOWN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TOWN_has_USER_TOWN1`
    FOREIGN KEY (`TOWN_ID`)
    REFERENCES `testdb`.`TOWN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TOWN_has_USER_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`PRODUCT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `status` VARCHAR(10) NOT NULL DEFAULT 'onsale',
  `category` VARCHAR(12) NOT NULL,
  `content` TEXT NOT NULL,
  `price` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  `USER_UID` INT NOT NULL,
  `TOWN_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `USER_UID`, `TOWN_ID`),
  INDEX `fk_PRODUCT_USER1_idx` (`USER_UID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_PRODUCT_TOWN1_idx` (`TOWN_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCT_TOWN1`
    FOREIGN KEY (`TOWN_ID`)
    REFERENCES `testdb`.`TOWN` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`PRODUCT_IMAGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `image_url` TEXT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`ID`, `PRODUCT_ID`),
  INDEX `fk_PRODUCT_IMAGES_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCT_IMAGES_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `testdb`.`PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `testdb`.`LIKE_LIST` (
  `USER_UID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  `timecreated` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`USER_UID`, `PRODUCT_ID`),
  INDEX `fk_USER_has_PRODUCT_USER1_idx` (`USER_UID` ASC) VISIBLE,
  INDEX `fk_USER_has_PRODUCT_PRODUCT1_idx` (`PRODUCT_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USER_has_PRODUCT_USER1`
    FOREIGN KEY (`USER_UID`)
    REFERENCES `testdb`.`USER` (`UID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_has_PRODUCT_PRODUCT1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `testdb`.`PRODUCT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);
